var GAME_LEVELS = [
  ["                                                             xvvx               ",
   "                                                                                ",
   "                                                     o                          ",
   "                                                                                ",
   "                                                   xxx                          ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                            xxx            xx                   ",
   "                                    o o                                         ",
   "                                                                                ",
   "                                                                                ",
   "                                  xxxxxx                                     x  ",
   "  xx         o                            o o         o                      x  ",
   "  x                     b                                                    x  ",
   "  x        xxxxx     xxxxx               xxxxx       xxx                   o x  ",
   "  x       x             o                                                    x  ",
   "  x  @   x                                       x!!!!!!!!!x     xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxx  ",
   "                              x   x                                             ",
   "                              x!!!x                                             ",
   "                              xxxxx                                             ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                               x                                   x                                              ",
   "                         xxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                         x                                                                                      x ",
   "                         x                        o                                                             x ",
   "                         x                                                                                      x ",
   "                         x                                                                                      x ",
   "                         x                     xxxxxxxx                                             o           x ",
   "                         x                                                                      x        x      x ",
   "                         x                                                  xxxxxxxxxxxxxxxxxxxxx        xxxxxxxx ",
   "                         x               =                      =           x                   x        x        ",
   "                         x                 o               o                x                   x        x        ",
   "                         x                         =                        x                   x        x        ",
   "                         xxxxxxxx        xxxxx            xxxx      xxxxxxxxx                   x        x        ",
   "                                x                                   x                           x        x        ",
   "                                x                                   x                           x        x        ",
   "xxxxxxxxxxxxxxxxxxxxxxxx        x                  o                x                           x        x        ",
   "x                      x        xxxxxxxxxxxxxxxx       xxxxxxxxxxxxxx                           x    o   x        ",
   "x                      x                       x       x                                        x        x        ",
   "x    @                 x                       x       x                                        x        x        ",
   "xxxxxxx       xxxxxxxxxx                       x   o   x                                        x        x        ",
   "      x       x                                x       x                                        x        x        ",
   "      x       x        x         x         x   x        x                                       x        x        ",
   "      x       x   x    v    x    v    x    v   x       x                                  xxxxxxx        x        ",
   "      x       x   v         v         v       x       x                                   x   o          x        ",
   "      x       xxxx xxxx xxxx xxxx xxxx xxxx xx       x                                    x              x        ",
   "      x              o    o    o    o    o      b   x                                     x!             x        ",
   "      x                                            x                                      xxxxxxxxxxxxxxxx        ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                               "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                o                                                                             ",
   "                                                                                                              ",
   "                               xxx                                                                            ",
   "          o                                                                                                   ",
   "                                                                                                              ",
   "         xxx                                               o            x            x           x            ",
   "                                                                    xxxxvxxxxxxxxxxxxvxxxxxxxxxxxvxxxxxxxxxxxx",
   "                                                          xxx       x                                         ",
   "                                                                    x        o                      =         ",
   "                                                                   xx               =           o             ",
   "                                                                                                              ",
   "                                                                         =     =         o                    ",
   "                                                                    x       o                                 ",
   "                                                                    x       =      =                   o      ",
   "    x           x        x                  b                       x                                         ",
   "xxxxvxxxxxxxxxxxvxxxxxxxxvx                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                         xxxxxxxx          x                                                  ",
   "                                                          x                                                   ",
   "                               o                         x                                                    ",
   "                                                        x                                                     ",
   "                              xxx                      x                                                      ",
   "                                                      x                                                       ",
   "            o                        xxx xxx     x xxxx                                                       ",
   "                                     x        =       x                                                       ",
   "           xxx             x         x                x                                                       ",
   "                                   xxx  o         o   x                                                       ",
   "                      o              x  x    x    x   x                                                       ",
   "                                     x!!!!!!!!!!!!!!!!x                                                       ",
   "                     xxx             xxxxxxxxxxxxxxxxxx                                                       ",
   "                                     x                                                                        ",
   "                                     x                                                                        ",
   "            o                        x                                                                        ",
   "                                     x                                                                        ",
   "           xxx                       x                                                                        ",
   "                                     x                                                                        ",
   "                                     x                                                                        ",
   "                                     x                                                                        ",
   "                                     x                                                                        ",
   "                                     x                                                                        ",
   "    @                                x                                                                        ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "          ooo  o   o   ooo   ooo  ooooo   ooo   ooo   o                                                       ",
   "         o     o   o  o     o     o      o     o      o                                                       ",
   "          oo   o   o  o     o     ooo     oo    o     o                                                      ",
   "            o  o   o  o     o     o         o     o                                                           ",
   "         oooo   ooo    ooo   ooo  ooooo  ooo   ooo    o                                                       ",
   "   @                                                                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
